### ISSUE TITLE
Using a Shared Store With Next

### ISSUE THREAD

**Issue by beardedtim** [beardedtim/rejection-app#2]
I am unsure of how to use Redux inside of Next without re-creating the store on each page change. I need to do some research into this.

**Comment by beardedtim** [comment]
It seems that `next` requires [more](https://github.com/zeit/next.js/blob/master/examples/with-redux/store.js#L33) and [more](https://github.com/zeit/next.js/blob/master/examples/with-redux/pages/other.js#L3) abstractions in exchange for taking care of SSR/Routing/some tooling. 

I am not 100% sure that this is worth the effort instead of writing a good webpack config and a good SSR script *when the need arises*.

**Comment by ericelliott** [comment]
I'm not sure what you mean. How are those links "more indirection" than you normally need with React and Redux?

In my experience, hooking up Redux with Next.js is simple: `withRedux(MyPageComponent)`

**Comment by beardedtim** [comment]
As of now, I haven't been able to get the UI to react to the update caused by dispatch. I can watch it go from the component to the reducer but cannot seem to get that update to be reflected in the props being passed to the component. 

You seem to know more about the boilerplate on this so let's plan on clarifying this boilerplate.

**Comment by beardedtim** [comment]
Resolved with last pair coding session.
